# Generated by Django 4.2.7 on 2023-12-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_commonskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonskills',
            name='skills',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
