# Generated by Django 4.2.7 on 2024-01-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_publicpostsaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpost',
            name='Comments',
            field=models.IntegerField(default=0),
        ),
    ]
