# Generated by Django 4.2.7 on 2024-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersnotifications_notifyuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
