# Generated by Django 4.2.7 on 2024-01-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_forgototp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgototp',
            old_name='otp',
            new_name='checkotp',
        ),
        migrations.RenameField(
            model_name='forgototp',
            old_name='user',
            new_name='email',
        ),
    ]
