# Generated by Django 4.2.7 on 2023-12-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
