# Generated by Django 4.2.7 on 2023-12-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_profile_id_education_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='Job_titile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
    ]
