# Generated by Django 4.2.7 on 2023-11-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_jobpost_is_available'),
        ('employee', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=250)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='job_Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('education_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.education')),
                ('job_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobpost')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.personalskills')),
            ],
        ),
    ]
