# Generated by Django 4.2.7 on 2023-11-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_personalskills_job_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personalskills',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
