# Generated by Django 4.2.7 on 2023-12-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_job_titile_employeeprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='Location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
