# Generated by Django 4.2.7 on 2023-12-21 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0006_employeeprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpost',
            name='profile',
        ),
        migrations.AddField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
