# Generated by Django 4.2.7 on 2023-12-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('employee', '0007_remove_savedpost_profile_savedpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalskills',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='personalskills',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_skills', to='employee.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='personalskills',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.commonskills'),
        ),
    ]
