# Generated by Django 4.2.7 on 2024-01-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_personalskills_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='ExpectedSalary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job_applications',
            name='Experience',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job_applications',
            name='currentSalary',
            field=models.IntegerField(null=True),
        ),
    ]
