# Generated by Django 4.2.7 on 2024-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_job_applications_expectedsalary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
