# Generated by Django 4.2.7 on 2024-01-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_job_applications_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_Education', to='employee.employeeprofile'),
        ),
    ]
