# Generated by Django 4.2.7 on 2024-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_education_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='Read',
            field=models.BooleanField(default=False),
        ),
    ]
