# Generated by Django 4.2.7 on 2024-01-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_job_applications_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applications',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
