# Generated by Django 4.2.7 on 2024-01-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_reportjobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='ApplicationStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
