# Generated by Django 4.2.7 on 2024-01-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_job_applications_applicationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applications',
            name='ApplicationStatus',
            field=models.CharField(blank=True, null=True),
        ),
    ]
