# Generated by Django 4.2.7 on 2024-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_job_applications_applicationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='Updated',
            field=models.BooleanField(default=False),
        ),
    ]
