# Generated by Django 4.2.7 on 2024-02-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_job_applications_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
    ]
