# Generated by Django 4.2.7 on 2023-12-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250, unique=True)),
                ('Industry', models.CharField(max_length=250)),
                ('Company_Size', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=250)),
                ('Address', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=250)),
                ('job_description', models.TextField()),
                ('Experience', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('Openings', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Required_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='company.jobpost')),
            ],
        ),
    ]
