# Generated by Django 4.2.7 on 2023-11-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_titile', models.CharField(max_length=250)),
                ('job_discription', models.TextField()),
                ('Experiance', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('requerd_skills', models.TextField()),
                ('salary', models.CharField(max_length=250)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
