# Generated by Django 4.2.7 on 2023-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
