# Generated by Django 4.2.7 on 2023-11-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
