# Generated by Django 4.2.7 on 2023-12-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Experience',
            field=models.PositiveIntegerField(),
        ),
    ]
