# Generated by Django 4.2.7 on 2023-12-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_jobpost_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Openings',
            field=models.IntegerField(null=True),
        ),
    ]
