# Generated by Django 4.2.7 on 2023-12-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_commonskills_skills'),
        ('company', '0004_jobpost_openings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='requerd_skills',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requerd_skills',
            field=models.ManyToManyField(to='users.commonskills'),
        ),
    ]
