# Generated by Django 4.2.7 on 2024-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_jobpost_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='ApplicationStatus',
            field=models.CharField(default='Pending'),
        ),
    ]
