# Generated by Django 4.2.7 on 2024-01-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_jobpost_applicationstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='ApplicationStatus',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='ApplicationCount',
            field=models.IntegerField(default=0),
        ),
    ]
