# Generated by Django 4.2.7 on 2023-12-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_jobpost_requerd_skills_jobpost_requerd_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Experiance',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Job_titile',
            new_name='Job_title',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='requerd_skills',
            new_name='required_skills',
        ),
    ]
