# Generated by Django 4.2.7 on 2023-12-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_experiance_jobpost_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_discription',
            new_name='job_description',
        ),
    ]
