# Generated by Django 4.2.7 on 2023-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_commonskills_skills'),
        ('company', '0007_rename_job_discription_jobpost_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.ManyToManyField(related_name='required_skills', to='users.commonskills'),
        ),
    ]
