# Generated by Django 4.2.7 on 2023-12-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_jobpost_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='required_skills',
        ),
    ]
