# Generated by Django 4.2.7 on 2023-12-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_commonskills_skills'),
        ('company', '0010_remove_jobpost_required_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Required_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='company.jobpost')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.commonskills')),
            ],
        ),
    ]
